# Generated by Django 4.1.3 on 2022-12-01 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_alter_payment_payment_id_alter_payment_user_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='order_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
