# Generated by Django 4.0.3 on 2022-04-27 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_users_date_remove_users_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='degree',
            new_name='first_name',
        ),
    ]
