# Generated by Django 4.0.3 on 2022-04-28 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_users_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
