# Generated by Django 4.0.3 on 2022-05-01 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_users_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
