# Generated by Django 4.0.3 on 2022-05-05 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_user_last_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('middle_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100, null=True)),
                ('date', models.DateField(null=True)),
                ('phone', models.BigIntegerField(null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('type', models.CharField(max_length=100, null=True)),
                ('degree', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='images')),
                ('password', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
