# Generated by Django 4.0.3 on 2022-05-05 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_profiles_delete_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profiles',
            new_name='Profile',
        ),
    ]
