# Generated by Django 4.0.3 on 2022-05-27 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_class_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('Lecture_id', models.AutoField(primary_key=True, serialize=False)),
                ('class_id', models.IntegerField()),
                ('subject_id', models.IntegerField()),
                ('teacher_id', models.IntegerField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
        ),
    ]
