# Generated by Django 4.0.3 on 2022-05-27 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_rename_lecture_id_lecture_lecture_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presenty',
            fields=[
                ('presenty_id', models.AutoField(primary_key=True, serialize=False)),
                ('lecture_id', models.IntegerField()),
                ('student_id', models.IntegerField()),
                ('presenty', models.CharField(max_length=100)),
            ],
        ),
    ]
