# Generated by Django 4.0.3 on 2022-05-28 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_presenty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecture',
            old_name='class_id',
            new_name='classid',
        ),
        migrations.RenameField(
            model_name='lecture',
            old_name='subject_id',
            new_name='subjectid',
        ),
        migrations.RenameField(
            model_name='presenty',
            old_name='lecture_id',
            new_name='lectu_id',
        ),
        migrations.RenameField(
            model_name='presenty',
            old_name='student_id',
            new_name='stud_id',
        ),
    ]
