# Generated by Django 4.0.3 on 2022-08-24 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_rename_class_id_lecture_classid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='presenty',
            old_name='presenty_id',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='lecture_id',
        ),
        migrations.AddField(
            model_name='lecture',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lecture',
            name='classid',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='subjectid',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='teacher_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='time',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='presenty',
            name='lectu_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='presenty',
            name='presenty',
            field=models.CharField(default=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='presenty',
            name='stud_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
