# Generated by Django 4.0.3 on 2022-08-24 12:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_rename_presenty_id_presenty_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='time',
        ),
        migrations.AlterField(
            model_name='lecture',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
