# Generated by Django 4.0.3 on 2022-08-24 12:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_remove_lecture_time_alter_lecture_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='time',
            field=models.DateTimeField(default=datetime.time(18, 7, 3, 943982)),
        ),
    ]
