# Generated by Django 4.0.3 on 2022-08-24 12:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_lecture_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='time',
            field=models.DateTimeField(default=datetime.time(18, 13, 36, 649005), verbose_name='expiration time (of ad)'),
        ),
    ]
