# Generated by Django 4.0.3 on 2022-08-24 12:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_alter_lecture_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='time',
            field=models.TimeField(default=datetime.time(18, 15, 46, 942065)),
        ),
    ]
