# Generated by Django 4.0.3 on 2022-08-24 12:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_alter_lecture_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
