# Generated by Django 4.0.3 on 2022-08-25 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_alter_lecture_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='date',
        ),
    ]
