# Generated by Django 4.0.3 on 2022-08-25 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_remove_lecture_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
