# Generated by Django 4.0.3 on 2022-08-25 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_lecture_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='date',
            field=models.CharField(default='', max_length=100),
        ),
    ]
