# Generated by Django 4.0.3 on 2022-10-18 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_alter_lecture_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
